name: Build for Windows

on:
  workflow_call:
    inputs:
      pkg_version:
        description: Build version
        required: true
        type: string

jobs:
  build:
    name: Build for Windows (${{ matrix.arch }}, ${{ matrix.configuration }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
        configuration: [release]
    container:
      image: ghcr.io/xemu-project/xemu-win64-toolchain-gcc:sha-18018f1
    defaults:
      run:
        shell: bash
    env:
      CCACHE_DIR: /tmp/xemu-ccache
      CCACHE_MAXSIZE: 512M
      LTO_CACHE_DIR: /tmp/xemu-lto-ccache
      CROSSPREFIX: x86_64-w64-mingw32.static-
      CROSSAR: x86_64-w64-mingw32.static-gcc-ar
    steps:
    - name: Download source package
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v4
      with:
        name: src
    - name: Extract source package
      run: tar -xf xemu-${{ inputs.pkg_version }}.tar.zst --strip-components=2
    - name: Initialize compiler cache
      id: cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v4
      with:
        path: |
          ${{ env.CCACHE_DIR }}
          ${{ env.LTO_CACHE_DIR }}
        key: cache-wincross-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.configuration }}-${{ github.sha }}
        restore-keys: cache-wincross-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.configuration }}-
    - name: Setup ccache
      run: |
        mkdir -p ${CCACHE_DIR}
        ccache -z
    - name: Setup build options
      run: |
        opts=(
          --extra-cflags="-flto-incremental=${LTO_CACHE_DIR} -flto-partition=cache"
          -Db_lto=true
        )
        mkdir -p ${LTO_CACHE_DIR}
        echo "XEMU_BUILD_OPTIONS=${opts[*]}" >> "$GITHUB_ENV"
    - name: Compile
      run: ./build.sh -p win64-cross ${XEMU_BUILD_OPTIONS}
    - name: Report ccache stats
      run: ccache -s
    - name: Package
      id: package
      env:
        VERSION: ${{ inputs.pkg_version }}
      run: |
        pkg_filename="xemu-${VERSION}-windows-${{ matrix.arch }}.zip"
        echo "pkg_filename=${pkg_filename}" >> $GITHUB_OUTPUT

        printf '[general.updates]\ncheck = false\n' > dist/xemu.toml

        pushd dist
        zip -9 -r ../${pkg_filename} *
        popd
    - name: Upload build artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
      with:
        name: xemu-windows-${{ matrix.arch }}-${{ matrix.configuration }}
        path: ${{ steps.package.outputs.pkg_filename }}
        compression-level: 0
